version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=zero2prod
      - POSTGRES_USER=zero2prod
      - POSTGRES_DB=zero2prod

